### ISSUE TITLE
sbctl: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by dnyaneshwar-m** [replicatedhq/sbctl#130]
Hello Team,

I am trying to install the application on linux as well as on ubuntu, After installing the sbctl when I try to run sbctl command as per doc its giving me error of Exec format error.

Is there any limitation of where it should be installed vs where not ?

```
[@localhost sbctl]$ sbctl
-bash: /usr/local/bin/sbctl: cannot execute binary file: Exec format error
[@localhost sbctl]$

```

**Comment by xavpaice** [comment]
Looks like the wrong binary - can you tell us how you downloaded and installed sbctl?  The binaries can be found in https://github.com/replicatedhq/sbctl/releases/tag/v0.9.1 for the current release.

**Comment by xavpaice** [comment]
since there's no response, I'll close this
