### ISSUE TITLE
Simplify syntax for starting a shell. 

### ISSUE THREAD

**Issue by danj-replicated** [replicatedhq/sbctl#136]
Current command syntax mandates the use of an `-s` flag to set the support bundle location, but since this flag is mandatory and can only be set once, it might make more sense to have the support bundle location be a positional argument. i.e:

```
sbctl shell /path/to/bundle

sbctl shell .

sbctl serve /path/to/bundle
```

**Comment by xavpaice** [comment]
related: #59 

How about we make `-s` optional, with a default of `./support-bundle.tar.gz`?
