### ISSUE TITLE
kubectl errors when process is sent to background

### ISSUE THREAD

**Issue by aj-jester** [replicatedhq/sbctl#37]
## Description
When the `sbctl` process is sent to background process, it outputs a error when running `kubectl`

```
2022/04/04 15:45:58 called getAPIV1ClusterResources
2022/04/04 15:45:58 failed to decode file, will try addind list GVK couldn't get version/kind; json parse error: json: cannot unmarshal array into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
2022/04/04 15:45:58 200 GET /api/v1/nodes?limit=500
```

## Reproduction Steps
* Send `sbctl` process to background using `&`.
  * `sbctl serve --support-bundle-location=supportbundle.tar.gz &`
* Run any `kubectl` command.
  * `kubectl get no`

## Expected Behavior
`sbctl` should generally handle when being used as a background process.

## Customer Impact
The impact is two fold.

* We have to have two terminals open or have a tmux/screen session open to get this to work without errors.
* The error message is too verbose and we are planning to use this in Kubecon EU, so would like to clean these up.

## Workaround
Open a Tmux session and start the `sbctl` in there to avoid being sent to background.

## Environment
`sbctl` `0.0.4`

## Additional Information
There is also a typo on this line https://github.com/replicatedhq/sbctl/blob/main/pkg/sbctl/compatibility.go#L28

**Comment by divolgin** [comment]
@aj-jester does https://github.com/replicatedhq/sbctl/pull/44 address the need for this?

**Comment by aj-jester** [comment]
Oh yah! Awesome! Thanks so much 🙏🏽

**Comment by aj-jester** [comment]
Hey @divolgin for some reason when I use `sbctl shell` it still gives these messages

```
aj@aj-cre-debug:/home/aj$ kubectl get po
2022/04/26 17:31:22 called getAPIV1NamespaceResources
2022/04/26 17:31:22 failed to decode file, will try addind list GVK couldn't get version/kind; json parse error: json: cannot unmarshal array into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
2022/04/26 17:31:22 200 GET /api/v1/namespaces/default/pods?limit=500
```
