### ISSUE TITLE
deterministic kubeconfig file name

### ISSUE THREAD

**Issue by aj-jester** [replicatedhq/sbctl#39]
## Problem to solve (Required)
Currently when `sbctl serve` is ran, the `kubeconfig` tmp file that is generates is random. When trying to automate in a wrapper script, this is difficult to know what the file name is to run the export command.

## Proposal
Would like to pass an additional flag and pass the path to the tmp file location so its more deterministic and can be in a wrapper script.

## Further details
The goal is to run a wrapper script and have it serve and export all in one go, so the end user only has to run `kubectl` command after running the wrapper script.

## Impact (importance/urgency) (Required)
Would like to have this by Kubecon EU because we would like to have a seamless experience when using `sbctl` and can get quickly up and running.

## What does business success look like, and how can we measure that?
When we can deterministically create the kubeconfig file.

**Comment by divolgin** [comment]
@aj-jester does https://github.com/replicatedhq/sbctl/pull/44 address the need for this?

**Comment by aj-jester** [comment]
This is great! Thank you! 🙏🏽
