### ISSUE TITLE
add support for resources from `get all` that are missing

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/sbctl#52]
- replicasets
- daemonsets
- replicationcontrollers
- jobs
- cronjobs
- HPAs
- PVs
- PVCs

**Comment by xavpaice** [comment]
Currently missing:

```
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding (get replicasets.apps)
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding (get cronjobs.batch)
```

The rest are complete.

**Comment by xavpaice** [comment]
https://app.shortcut.com/replicated/story/109471/sbctl-add-replicasets-and-cronjobs

**Comment by diamonwiggins** [comment]
@xavpaice this looks good to me on the latest version. Will let you confirm before we close this out.
