### ISSUE TITLE
Add release packages for arm64

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/sbctl#54]
It's possible to build the binary on an M1 Mac, but it would be great if the binaries for that arch were automatically generated.

**Comment by edgarlanting** [comment]
This looks to be done @xavpaice am I right?

**Comment by CpuID** [comment]
Looks like https://github.com/replicatedhq/sbctl/commit/621094c19e192efce593e85c54d3de51c70c74dd added the option to goreleaser on Oct 18th, last release v0.9.0 was on Sep 9th. We'll find out next release I suspect :)

Success criteria: when viewing https://github.com/replicatedhq/sbctl/releases seeing a `sbctl_darwin_arm64.tar.gz` artifact.

**Comment by CpuID** [comment]
Fixed in https://github.com/replicatedhq/sbctl/releases/tag/v0.9.1
