### ISSUE TITLE
Add support for roles, clusterroles and clusterrole-bindings

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/sbctl#60]
https://github.com/replicatedhq/troubleshoot/pull/779 introduced collecting roles, clusterroles and clusterrole-bindings, these endpoints are not yet put into the sbctl code.  Let's add them there.

**Comment by edgarlanting** [comment]
Working on the implementation in here, please mind that this is still a draft PR and needs cleaning up. 

https://github.com/replicatedhq/sbctl/pull/64

**Comment by edgarlanting** [comment]
PR https://github.com/replicatedhq/sbctl/pull/64 is ready for review...
