### ISSUE TITLE
OpenLens / Lens / k9s

### ISSUE THREAD

**Issue by sj-porter-knime** [replicatedhq/sbctl#75]
Hey there, does anyone know how to get this utility working with k9s or Lens / OpenLens? A couple of us on our team gave it a try and none of us were able to connect using those tools. Seems like it'd be possible, though...

**Comment by xavpaice** [comment]
I think there's some functionality missing from the sbctl implementation that some tools would be looking for  - `kubectl get all` produces a similar result.

Is there some detailed error messages you could share that might help us to identify the missing API calls?

**Comment by sj-porter-knime** [comment]
Here's what I'm seeing. On the left is a terminal running sbctl and on the right is k9s. The k9s error is pretty generic.

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/86624823/236022125-ca5712d9-d73e-4f08-9679-0cfa46a2e11e.png">

In OpenLens:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/86624823/236023255-0a8ee299-ac8a-4372-80a9-6e0198427a89.png">

Corresponding sbctl logs for the openlens attempts (repeated errors are due to retries)

<img width="766" alt="image" src="https://user-images.githubusercontent.com/86624823/236023426-49bfa457-eee1-497d-a3bf-96754f3f15a1.png">

**Comment by sj-porter-knime** [comment]
How I attempted to connect:

- For k9s I simply exported the `KUBECONFIG` variable in the terminal I wanted to use then ran `k9s`. 
- For OpenLens I copied the contents out of the generated kubeconfig file and pasted it into OpenLens.

**Comment by banjoh** [comment]
FYI, I managed to get `k9s` working to some extent as part of https://github.com/replicatedhq/sbctl/pull/125 changes. I have not tested thoroughly so do expect some strange behaviours still

**Comment by xavpaice** [comment]
We've done some testing with current bundles and current k9s, and things appear to work well.

If there's something specific that is missing let us know!

I'll close this one for now.
